KalbeTest/KalbeTest.Web/Controllers/CostumerController.cs
using kalbetest.datamodels;
using kalbetest.viewmodels;
using KalbeTest.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace KalbeTest.Web.Controllers
{
	public class CostumerController : Controller
	{
		private CostumerService costumerService;
		public CostumerController(CostumerService _costumerService)
		{
			this.costumerService = _costumerService;

		}
		public async Task<IActionResult> Index(string sortOrder,
												string searchString,
												string currentFilter,
												int? pageNumber,
												int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			List<TblCostumer> data = await costumerService.GetAllData();

			if (!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.CostumerName.ToLower().Contains(searchString.ToLower())
				|| a.CostumerAddress.ToLower().Contains(searchString.ToLower())
				).ToList();
			}
			switch (sortOrder)
			{
				case "name_desc":
					data = data.OrderByDescending(a => a.CostumerName).ToList();
					break;
				default:
					data = data.OrderBy(a => a.CostumerName).ToList();
					break;
			}
			return View(PaginationList<TblCostumer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
		}

		public IActionResult Create()
		{
			TblCostumer data = new TblCostumer();
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> Create(TblCostumer dataParam)
		{

			VMResponse respon = await costumerService.Create(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

		public async Task<IActionResult> Edit(int id)
		{
			TblCostumer data = await costumerService.GetDataById(id);
			return PartialView(data);
		}
		[HttpPost]
		public async Task<IActionResult> Edit(TblCostumer dataParam)
		{

			VMResponse respon = await costumerService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}
		
        public async Task<IActionResult> Delete(int id)
        {
            TblCostumer data = await costumerService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int CostumerId)
        {
            
            VMResponse respon = await costumerService.Delete(CostumerId);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", CostumerId);
        }
		public async Task<IActionResult> Detail(int id)
		{
			TblCostumer data = await costumerService.GetDataById(id);
			return PartialView(data);
		}

	}
}

KalbeTest/KalbeTest.Web/Controllers/PenjualanController.cs
using kalbetest.viewmodels;
using kalbetest.datamodels;
using KalbeTest.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace KalbeTest.Web.Controllers
{
	public class PenjualanController : Controller
	{
		private ProdukService produkService;
		private CostumerService costumerService;
		private PenjualanService penjualanService;

		public PenjualanController(ProdukService _produkService, CostumerService _costumerService, PenjualanService _penjualanService)
		{
			this.produkService = _produkService;
			this.costumerService = _costumerService;
			this.penjualanService = _penjualanService;
		}

		public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.CurrentPageSize = pageSize;
			ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				pageNumber = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			List<VMTblPenjualan> data = await penjualanService.GetAllData();

			if (!string.IsNullOrEmpty(searchString))
			{
				data = data.Where(a => a.CostumerName.ToLower().Contains(searchString.ToLower())
				|| a.ProductName.ToLower().Contains(searchString.ToLower())
			 ).ToList();
			}

			switch (sortOrder)
			{
				case "name_desc":
					data = data.OrderByDescending(a => a.CostumerName).ToList();
					break;
				default:
					data = data.OrderBy(a => a.CostumerName).ToList();
					break;
			}

			return View(PaginationList<VMTblPenjualan>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
		}

		public async Task<IActionResult> Create()
		{
			VMTblPenjualan data = new VMTblPenjualan();

			List<TblProduk> listProduk = await produkService.GetAllData();
			ViewBag.ListProduk = listProduk;

			List<TblCostumer> listCostumer = await costumerService.GetAllData();
			ViewBag.ListCostumer = listCostumer;

			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> Create(VMTblPenjualan dataParam)
		{
			VMResponse respon = await penjualanService.Create(dataParam);

			if (respon.Success)
			{	
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

		public async Task<IActionResult> Edit(int id)
		{
            VMTblPenjualan data = await penjualanService.GetDataById(id);

            List<TblProduk> listProduk = await produkService.GetAllData();
            ViewBag.ListProduk = listProduk;

            List<TblCostumer> listCostumer = await costumerService.GetAllData();
            ViewBag.ListCostumer = listCostumer;

            return PartialView(data);
        }

		[HttpPost]
		public async Task<IActionResult> Edit(VMTblPenjualan dataParam)
		{
			VMResponse respon = await penjualanService.Edit(dataParam);

			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}

			return View(dataParam);
		}

		public async Task<IActionResult> Delete(int id)
		{
			VMTblPenjualan data = await penjualanService.GetDataById(id);
			return PartialView(data);
		}

		[HttpPost]
		public async Task<IActionResult> SureDelete(int SalesOrderId)
		{
			VMResponse respon = await penjualanService.Delete(SalesOrderId);

			if (respon.Success)
			{
				return RedirectToAction("Index");
			}
			return RedirectToAction("Index", SalesOrderId);
		}

		public async Task<IActionResult> Detail(int id)
		{
			VMTblPenjualan data = await penjualanService.GetDataById(id);

            List<TblProduk> listProduk = await produkService.GetAllData();
            ViewBag.ListProduk = listProduk;

            List<TblCostumer> listCostumer = await costumerService.GetAllData();
            ViewBag.ListCostumer = listCostumer;

            return PartialView(data);
		}
	}
}

KalbeTest/KalbeTest.Web/Controllers/ProdukController.cs
using kalbetest.viewmodels;
using Microsoft.AspNetCore.Mvc;
using kalbetest.datamodels;
using KalbeTest.Web.Services;

namespace Kalbetest.Web.Controllers
{
    public class ProdukController : Controller
    {
        private ProdukService produkService;
        public ProdukController(ProdukService _produkService)
        {
            this.produkService = _produkService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblProduk> data = await produkService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.ProductCode.ToLower().Contains(searchString.ToLower())
                || a.ProductName.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.ProductCode).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.ProductCode).ToList();
                    break;
            }
            return View(PaginationList<TblProduk>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            TblProduk data = new TblProduk();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(TblProduk dataParam)
        {
            
            VMResponse respon = await produkService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
      
        public async Task<IActionResult> Edit(int id)
        {
            TblProduk data = await produkService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TblProduk dataParam)
        {
            
            VMResponse respon = await produkService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblProduk data = await produkService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            
            VMResponse respon = await produkService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            TblProduk data = await produkService.GetDataById(id);
            return PartialView(data);
        }

    }
}

KalbeTest/KalbeTest.Web/Views/Shared/_Header.cshtml
﻿<!-- ============================================================== -->
<!-- Topbar header - style you can find in pages.scss -->
<!-- ============================================================== -->
<header class="topbar" data-navbarbg="skin6">
	<nav class="navbar top-navbar navbar-expand-md">
		<div class="navbar-header" data-logobg="skin6">
			<!-- This is for the sidebar toggle which is visible on mobile only -->
			<a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
				<i class="ti-menu ti-close"></i>
			</a>
			<!-- ============================================================== -->
			<!-- Logo -->
			<!-- ============================================================== -->
			<div class="navbar-brand">
				<!-- Logo icon -->
				<a href="~/Home/Index">
					<b class="logo-icon">
						<!-- Dark Logo icon -->
						<img src="~/adminmart/assets/images/kalbe.png" width="150" height="100" alt="homepage" class="dark-logo" />
						<!-- Light Logo icon -->
						<img src="~/adminmart/assets/images/kalbe.png" alt="homepage" class="light-logo" />
					</b>
					<!--End Logo icon -->
					<!-- Logo text -->
					@*<span class="logo-text">
						<!-- dark Logo text -->
						<img src="~/adminmart/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
						<!-- Light Logo text -->
						<img src="~/adminmart/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
					</span>*@
				</a>
			</div>
			<!-- ============================================================== -->
			<!-- End Logo -->
			<!-- ============================================================== -->
			<!-- ============================================================== -->
			<!-- Toggle which is visible on mobile only -->
			<!-- ============================================================== -->
			<a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
			   data-toggle="collapse" data-target="#navbarSupportedContent"
			   aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<i class="ti-more"></i>
			</a>
		</div>
		<!-- ============================================================== -->
		<!-- End Logo -->
		<!-- ============================================================== -->
		<div class="navbar-collapse collapse" id="navbarSupportedContent">
			<!-- ============================================================== -->
			<!-- toggle and nav items -->
			<!-- ============================================================== -->
			<ul class="navbar-nav float-left mr-auto ml-3 pl-1">
				<!-- Notification -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle pl-md-3 position-relative" href="javascript:void(0)"
					   id="bell" role="button" data-toggle="dropdown" aria-haspopup="true"
					   aria-expanded="false">
						<span><i data-feather="bell" class="svg-icon"></i></span>
						<span class="badge badge-primary notify-no rounded-circle">5</span>
					</a>
					<div class="dropdown-menu dropdown-menu-left mailbox animated bounceInDown">
						<ul class="list-style-none">
							<li>
								<div class="message-center notifications position-relative">
									<!-- Message -->
									<a href="javascript:void(0)"
									   class="message-item d-flex align-items-center border-bottom px-3 py-2">
										<div class="btn btn-danger rounded-circle btn-circle">
											<i data-feather="airplay" class="text-white"></i>
										</div>
										<div class="w-75 d-inline-block v-middle pl-2">
											<h6 class="message-title mb-0 mt-1">Luanch Admin</h6>
											<span class="font-12 text-nowrap d-block text-muted">
												Just see
												the my new
												admin!
											</span>
											<span class="font-12 text-nowrap d-block text-muted">9:30 AM</span>
										</div>
									</a>
									<!-- Message -->
									<a href="javascript:void(0)"
									   class="message-item d-flex align-items-center border-bottom px-3 py-2">
										<span class="btn btn-success text-white rounded-circle btn-circle">
											<i data-feather="calendar" class="text-white"></i>
										</span>
										<div class="w-75 d-inline-block v-middle pl-2">
											<h6 class="message-title mb-0 mt-1">Event today</h6>
											<span class="font-12 text-nowrap d-block text-muted text-truncate">
												Just
												a reminder that you have event
											</span>
											<span class="font-12 text-nowrap d-block text-muted">9:10 AM</span>
										</div>
									</a>
									<!-- Message -->
									<a href="javascript:void(0)"
									   class="message-item d-flex align-items-center border-bottom px-3 py-2">
										<span class="btn btn-info rounded-circle btn-circle">
											<i data-feather="settings" class="text-white"></i>
										</span>
										<div class="w-75 d-inline-block v-middle pl-2">
											<h6 class="message-title mb-0 mt-1">Settings</h6>
											<span class="font-12 text-nowrap d-block text-muted text-truncate">
												You
												can customize this template
												as you want
											</span>
											<span class="font-12 text-nowrap d-block text-muted">9:08 AM</span>
										</div>
									</a>
									<!-- Message -->
									<a href="javascript:void(0)"
									   class="message-item d-flex align-items-center border-bottom px-3 py-2">
										<span class="btn btn-primary rounded-circle btn-circle">
											<i data-feather="box" class="text-white"></i>
										</span>
										<div class="w-75 d-inline-block v-middle pl-2">
											<h6 class="message-title mb-0 mt-1">Pavan kumar</h6> <span class="font-12 text-nowrap d-block text-muted">
												Just
												see the my admin!
											</span>
											<span class="font-12 text-nowrap d-block text-muted">9:02 AM</span>
										</div>
									</a>
								</div>
							</li>
							<li>
								<a class="nav-link pt-3 text-center text-dark" href="javascript:void(0);">
									<strong>Check all notifications</strong>
									<i class="fa fa-angle-right"></i>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<!-- End Notification -->
				<!-- ============================================================== -->
				<!-- create new -->
				<!-- ============================================================== -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
					   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i data-feather="settings" class="svg-icon"></i>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#">Action</a>
						<a class="dropdown-item" href="#">Another action</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Something else here</a>
					</div>
				</li>
				<li class="nav-item d-none d-md-block">
					<a class="nav-link" href="javascript:void(0)">
						<div class="customize-input">
							<select class="custom-select form-control bg-white custom-radius custom-shadow border-0">
								<option selected>EN</option>
								<option value="1">AB</option>
								<option value="2">AK</option>
								<option value="3">BE</option>
							</select>
						</div>
					</a>
				</li>
			</ul>
			<!-- ============================================================== -->
			<!-- Right side toggle and nav items -->
			<!-- ============================================================== -->
			<ul class="navbar-nav float-right">
				<!-- ============================================================== -->
				<!-- Search -->
				<!-- ============================================================== -->
				<li class="nav-item d-none d-md-block">
					<a class="nav-link" href="javascript:void(0)">
						<form>
							<div class="customize-input">
								<input class="form-control custom-shadow custom-radius border-0 bg-white"
									   type="search" placeholder="Search" aria-label="Search">
								<i class="form-control-icon" data-feather="search"></i>
							</div>
						</form>
					</a>
				</li>
				<!-- ============================================================== -->
				<!-- User profile and search -->
				<!-- ============================================================== -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
					   aria-haspopup="true" aria-expanded="false">
						<img src="~/adminmart/assets/images/users/d3.jpg" alt="user" class="rounded-circle"
		width="40">
						<span class="ml-2 d-none d-lg-inline-block">
							<span>Hello,</span> <span class="text-dark">Alwi Fadli S</span> <i data-feather="chevron-down"
																						class="svg-icon"></i>
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
						<a class="dropdown-item" href="javascript:void(0)">
							<i data-feather="user"
							   class="svg-icon mr-2 ml-1"></i>
							My Profile
						</a>
						<a class="dropdown-item" href="javascript:void(0)">
							<i data-feather="credit-card"
							   class="svg-icon mr-2 ml-1"></i>
							My Balance
						</a>
						<a class="dropdown-item" href="javascript:void(0)">
							<i data-feather="mail"
							   class="svg-icon mr-2 ml-1"></i>
							Inbox
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="javascript:void(0)">
							<i data-feather="settings"
							   class="svg-icon mr-2 ml-1"></i>
							Account Setting
						</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="javascript:void(0)">
							<i data-feather="power"
							   class="svg-icon mr-2 ml-1"></i>
							Logout
						</a>
						<div class="dropdown-divider"></div>
						<div class="pl-4 p-3">
							<a href="javascript:void(0)" class="btn btn-sm btn-info">
								View
								Profile
							</a>
						</div>
					</div>
				</li>
				<!-- ============================================================== -->
				<!-- User profile and search -->
				<!-- ============================================================== -->
			</ul>
		</div>
	</nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->	

KalbeTest/KalbeTest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XSIS Mitra Utama</title>
    <!-- JQuery -->
    <script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="50x50" href="~/adminmart/assets/images/kalbe.png">
    <!-- Custom CSS -->
    <link href="~/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/adminmart/dist/css/style.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">

</head>
<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

        <partial name="_Header" />
        <partial name="_Sidebar" />

        <div class="page-wrapper">

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2023 by alwifs - XSIS Mitra Utama - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="myModal_body">
                        ...
                    </div>

                </div>
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="modal_sm" tabindex="-1"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-body" id="modal_body_sm">
                        ...
                    </div>
                </div>
            </div>
        </div>

        <!-- All Jquery -->
        <!-- ============================================================== -->

        <script src="~/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
        <script src="~/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- apps -->
        <!-- apps -->
        <script src="~/adminmart/dist/js/app-style-switcher.js"></script>
        <script src="~/adminmart/dist/js/feather.min.js"></script>
        <script src="~/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
        <script src="~/adminmart/dist/js/sidebarmenu.js"></script>
        <!--Custom JavaScript -->
        <script src="~/adminmart/dist/js/custom.min.js"></script>
        <!--This page JavaScript -->
        <script src="~/adminmart/assets/extra-libs/c3/d3.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/c3/c3.min.js"></script>
        <script src="~/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
        <script src="~/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
        <script src="~/adminmart/dist/js/pages/dashboards/dashboard1.min.js"></script>

</body>
</html>

KalbeTest/KalbeTest.Web/Views/Shared/_Sidebar.cshtml
﻿<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Produk" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Product</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Costumer" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-user"></i><span class="hide-menu">Costumer</span>
                    </a>
                </li>



                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Penjualan" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Menu Penjualan</span>
                    </a>
                </li>
                

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->